services:
  # ---- Backend (Spring Boot) ----
  - type: web
    name: studyplanner-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: singapore
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: studyplanner-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: studyplanner-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: studyplanner-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: studyplanner-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: studyplanner-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: CORS_ORIGINS
        value: https://studyplanner-web.onrender.com
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: PORT
        value: "10000"

  # ---- Frontend (React + Nginx) ----
  - type: web
    name: studyplanner-web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    region: singapore
    envVars:
      - key: REACT_APP_API_URL
        value: https://studyplanner-api-o2qn.onrender.com/api

databases:
  - name: studyplanner-db
    plan: free
    region: singapore
    databaseName: studyplanner
    user: studyplanner_user
